version: '3.8'
services:

  db:
    image: postgres:14
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sql_app
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} || exit 1
      interval: 5s
      retries: 3
      timeout: 5s

  app:
    build: .
    container_name: app
    volumes:
      - ./app:/src/app
    ports:
      - 8000:8000
    # environment:
    #   -
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-store:
